version: '2.1'

networks:
  monitor-net:
    driver: bridge

volumes:
    prometheus_data: {}
    grafana_data: {}

services:

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    expose:
      - 9090
    networks:
      - monitor-net
    labels:
      - org.label-schema.group=monitoring
      - traefik.docker.network=traefik-proxy
      - traefik.enable=true
      - traefik.http.middlewares.prometheus-https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.prometheus-secure.entrypoints=https
      - traefik.http.routers.prometheus-secure.rule=Host(`prometheus.thievent.org`)
      - traefik.http.routers.prometheus-secure.service=prometheus
      - traefik.http.routers.prometheus-secure.tls=true
      - traefik.http.routers.prometheus-secure.tls.certresolver=http
      - traefik.http.routers.prometheus.entrypoints=http
      - traefik.http.routers.prometheus.middlewares=prometheus-https-redirect
      - traefik.http.routers.prometheus.rule=Host(`prometheus.thievent.org`)
      - traefik.http.services.prometheus.loadbalancer.server.port=9090

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
      - ./alertmanager:/etc/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    restart: unless-stopped
    expose:
      - 9093
    networks:
      - monitor-net
    labels:
      - org.label-schema.group=monitoring
      - traefik.docker.network=traefik-proxy
      - traefik.enable=true
      - traefik.http.middlewares.am-https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.am-secure.entrypoints=https
      - traefik.http.routers.am-secure.rule=Host(`am.thievent.org`)
      - traefik.http.routers.am-secure.service=am
      - traefik.http.routers.am-secure.tls=true
      - traefik.http.routers.am-secure.tls.certresolver=http
      - traefik.http.routers.am.entrypoints=http
      - traefik.http.routers.am.middlewares=am-https-redirect
      - traefik.http.routers.am.rule=Host(`am.thievent.org`)
      - traefik.http.services.am.loadbalancer.server.port=9093

  nodeexporter:
    image: prom/node-exporter:latest
    container_name: nodeexporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    expose:
      - 9100
    networks:
      - monitor-net
    labels:
      - org.label-schema.group=monitoring
      - traefik.docker.network=traefik-proxy
      - traefik.enable=true
      - traefik.http.middlewares.nodeex-https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.nodeex-secure.entrypoints=https
      - traefik.http.routers.nodeex-secure.rule=Host(`nodeex.thievent.org`)
      - traefik.http.routers.nodeex-secure.service=nodeex
      - traefik.http.routers.nodeex-secure.tls=true
      - traefik.http.routers.nodeex-secure.tls.certresolver=http
      - traefik.http.routers.nodeex.entrypoints=http
      - traefik.http.routers.nodeex.middlewares=nodeex-https-redirect
      - traefik.http.routers.nodeex.rule=Host(`nodeex.thievent.org`)
      - traefik.http.services.nodeex.loadbalancer.server.port=9100

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      #- /cgroup:/cgroup:ro #doesn't work on MacOS only for Linux
    restart: unless-stopped
    expose:
      - 8080
    networks:
      - monitor-net
    labels:
      - org.label-schema.group=monitoring
      - traefik.docker.network=traefik-proxy
      - traefik.enable=true
      - traefik.http.middlewares.cadvisor-https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.cadvisor-secure.entrypoints=https
      - traefik.http.routers.cadvisor-secure.rule=Host(`cadvisor.thievent.org`)
      - traefik.http.routers.cadvisor-secure.service=cadvisor
      - traefik.http.routers.cadvisor-secure.tls=true
      - traefik.http.routers.cadvisor-secure.tls.certresolver=http
      - traefik.http.routers.cadvisor.entrypoints=http
      - traefik.http.routers.cadvisor.middlewares=cadvisor-https-redirect
      - traefik.http.routers.cadvisor.rule=Host(`cadvisor.thievent.org`)
      - traefik.http.services.cadvisor.loadbalancer.server.port=8080

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    expose:
      - 3000
    networks:
      - monitor-net
    labels:
      - org.label-schema.group=monitoring
      - traefik.docker.network=traefik-proxy
      - traefik.enable=true
      - traefik.http.middlewares.grafana-https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.grafana-secure.entrypoints=https
      - traefik.http.routers.grafana-secure.rule=Host(`grafana.thievent.org`)
      - traefik.http.routers.grafana-secure.service=grafana
      - traefik.http.routers.grafana-secure.tls=true
      - traefik.http.routers.grafana-secure.tls.certresolver=http
      - traefik.http.routers.grafana.entrypoints=http
      - traefik.http.routers.grafana.middlewares=grafana-https-redirect
      - traefik.http.routers.grafana.rule=Host(`grafana.thievent.org`)
      - traefik.http.services.grafana.loadbalancer.server.port=3000

  pushgateway:
    image: prom/pushgateway:latest
    container_name: pushgateway
    restart: unless-stopped
    expose:
      - 9091
    networks:
      - monitor-net
    labels:
      - org.label-schema.group=monitoring
      - traefik.docker.network=traefik-proxy
      - traefik.enable=true
      - traefik.http.middlewares.pgw-https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.pgw-secure.entrypoints=https
      - traefik.http.routers.pgw-secure.rule=Host(`pgw.thievent.org`)
      - traefik.http.routers.pgw-secure.service=pgw
      - traefik.http.routers.pgw-secure.tls=true
      - traefik.http.routers.pgw-secure.tls.certresolver=http
      - traefik.http.routers.pgw.entrypoints=http
      - traefik.http.routers.pgw.middlewares=pgw-https-redirect
      - traefik.http.routers.pgw.rule=Host(`pgw.thievent.org`)
      - traefik.http.services.pgw.loadbalancer.server.port=9091